/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package advanced.java.course.project.program;
    import java.sql.Connection;
    import java.sql.Statement;
    import java.sql.DriverManager;
    import java.sql.ResultSet;
    import java.sql.ResultSetMetaData;
    import java.sql.SQLException;
    import javax.swing.JOptionPane;
    import java.text.DecimalFormat;


/**
 *
 * @author pierr
 */
public class InventoryJFrame extends javax.swing.JFrame {

    /**
     * Creates new form InventoryJFrame
     */
    
    private static final String DB_URL = "jdbc:derby://localhost:1527/projectdb";
    DecimalFormat f = new DecimalFormat("###,###");
    
    public InventoryJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sclpSeeInventory = new javax.swing.JScrollPane();
        pnlSeeInventory = new javax.swing.JPanel();
        lblInventory = new javax.swing.JLabel();
        lblResults = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventory");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(400, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        sclpSeeInventory.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sclpSeeInventory.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlSeeInventory.setPreferredSize(new java.awt.Dimension(375, 750));

        lblInventory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInventory.setText("Inventory");

        javax.swing.GroupLayout pnlSeeInventoryLayout = new javax.swing.GroupLayout(pnlSeeInventory);
        pnlSeeInventory.setLayout(pnlSeeInventoryLayout);
        pnlSeeInventoryLayout.setHorizontalGroup(
            pnlSeeInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeeInventoryLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblResults, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(pnlSeeInventoryLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(lblInventory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSeeInventoryLayout.setVerticalGroup(
            pnlSeeInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeeInventoryLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblInventory)
                .addGap(18, 18, 18)
                .addComponent(lblResults, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap(633, Short.MAX_VALUE))
        );

        sclpSeeInventory.setViewportView(pnlSeeInventory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sclpSeeInventory, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sclpSeeInventory, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try
        {
            Connection conn = DriverManager.getConnection(DB_URL, "username", "password");
            Statement stmt = conn.createStatement();
            String sqlStmt = "SELECT * FROM Inventory";
            ResultSet result = stmt.executeQuery(sqlStmt);
            
            String results = "<html>";

            while (result.next())
            {
                results += "ID: " + result.getObject(1) +
                           "<br/>Description: " + result.getObject(2) +
                           "<br/>Price: $" + f.format(result.getObject(3)) +
                           "<br/># in Stock: " + f.format(result.getObject(4)) +
                           "<br/>Year: " + result.getObject(5) +
                           "<br/>Color: " + result.getObject(6) +
                           "<br/><br/>";
            }
            
            results += "</html>";
            lblResults.setText(results);
            
            conn.close();
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "There was an error loading the database:\n" + ex.getMessage(),
                                          "SQL Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "There was an error:\n" + ex.getMessage(),
                                          "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblInventory;
    private javax.swing.JLabel lblResults;
    private javax.swing.JPanel pnlSeeInventory;
    private javax.swing.JScrollPane sclpSeeInventory;
    // End of variables declaration//GEN-END:variables
}
