/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package advanced.java.course.project.program;
    import java.sql.Connection;
    import java.sql.Statement;
    import java.sql.DriverManager;
    import java.sql.ResultSet;
    import java.sql.ResultSetMetaData;
    import java.sql.SQLException;
    import javax.swing.JOptionPane;
    import java.text.DecimalFormat;
/**
 *
 * @author pierr
 */
public class SearchOrdersJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustOrdersJFrame
     */
    
    private static final String DB_URL = "jdbc:derby://localhost:1527/projectdb";
    DecimalFormat f = new DecimalFormat("###,###");
    
    public SearchOrdersJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sclpSearchOrders = new javax.swing.JScrollPane();
        pnlSearchOrders = new javax.swing.JPanel();
        lblPrompt = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblResults = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Orders");

        sclpSearchOrders.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sclpSearchOrders.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlSearchOrders.setPreferredSize(new java.awt.Dimension(400, 750));

        lblPrompt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrompt.setText("Search Orders By Customer ID");

        lblID.setText("ID to Search for:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearchOrdersLayout = new javax.swing.GroupLayout(pnlSearchOrders);
        pnlSearchOrders.setLayout(pnlSearchOrdersLayout);
        pnlSearchOrdersLayout.setHorizontalGroup(
            pnlSearchOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchOrdersLayout.createSequentialGroup()
                .addGroup(pnlSearchOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearchOrdersLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(pnlSearchOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResults, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlSearchOrdersLayout.createSequentialGroup()
                                .addComponent(lblID)
                                .addGap(18, 18, 18)
                                .addGroup(pnlSearchOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlSearchOrdersLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblPrompt)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        pnlSearchOrdersLayout.setVerticalGroup(
            pnlSearchOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchOrdersLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblPrompt)
                .addGap(18, 18, 18)
                .addGroup(pnlSearchOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addGap(29, 29, 29)
                .addComponent(lblResults, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap(590, Short.MAX_VALUE))
        );

        sclpSearchOrders.setViewportView(pnlSearchOrders);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sclpSearchOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sclpSearchOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try
        {
            Connection conn = DriverManager.getConnection(DB_URL, "username", "password");
            Statement stmt = conn.createStatement();

            if (txtID.getText().trim().matches("[0-9]{5}"))
            {
                String sqlStmt = "SELECT Sale.ID, Customer.Name, Sale.SaleDate, Inventory.Price "
                               + "FROM ((Sale "
                               + "INNER JOIN Customer ON Sale.CustID = Customer.ID)"
                               + "INNER JOIN Inventory ON Sale.InventoryID = Inventory.ID)"
                               + "WHERE Customer.ID = '" + txtID.getText().trim() + "'";
                ResultSet result = stmt.executeQuery(sqlStmt);

                String results = "<html>";

                while (result.next())
                {
                    results += "Order ID: " + result.getObject(1) +
                    "<br/>Name: " + result.getObject(2) +
                    "<br/>Sale Date: " + result.getObject(3) +
                    "<br/>Price: $" + f.format(result.getObject(4)) +
                    "<br/><br/>";
                }

                results += "</html>";

                if (results.equals("<html></html>"))
                    results = "No orders found for a customer with this ID.";

                lblResults.setText(results);
                
                conn.close();
            }
            else
            JOptionPane.showMessageDialog(this, "Invalid Input for ID:\nPlease enter a 5 number sequence.",
                "Invalid Input", JOptionPane.WARNING_MESSAGE);
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "There was an error loading the database:\n" + ex.getMessage(),
                "SQL Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "There was an error:\n" + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchOrdersJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchOrdersJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchOrdersJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchOrdersJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchOrdersJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPrompt;
    private javax.swing.JLabel lblResults;
    private javax.swing.JPanel pnlSearchOrders;
    private javax.swing.JScrollPane sclpSearchOrders;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
