/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package advanced.java.course.project.program;
    import java.sql.Connection;
    import java.sql.Statement;
    import java.sql.DriverManager;
    import java.sql.ResultSet;
    import java.sql.ResultSetMetaData;
    import java.sql.SQLException;
    import javax.swing.JOptionPane;
    import java.text.DecimalFormat;

/**
 *
 * @author pierr
 */
public class SearchNameJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SearchNameJFrame
     */
    
    private static final String DB_URL = "jdbc:derby://localhost:1527/projectdb";
    DecimalFormat f = new DecimalFormat("###,###");
    
    public SearchNameJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sclpSearchName = new javax.swing.JScrollPane();
        pnlSearchName = new javax.swing.JPanel();
        lblPrompt = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblResults = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Customer Name");

        sclpSearchName.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sclpSearchName.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlSearchName.setPreferredSize(new java.awt.Dimension(400, 750));

        lblPrompt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrompt.setText("Search Customers By Name");

        lblName.setText("Name to Search for:");

        txtName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNameCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout pnlSearchNameLayout = new javax.swing.GroupLayout(pnlSearchName);
        pnlSearchName.setLayout(pnlSearchNameLayout);
        pnlSearchNameLayout.setHorizontalGroup(
            pnlSearchNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchNameLayout.createSequentialGroup()
                .addGroup(pnlSearchNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSearchNameLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(lblPrompt)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSearchNameLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(pnlSearchNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResults, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlSearchNameLayout.createSequentialGroup()
                                .addComponent(lblName)
                                .addGap(18, 18, 18)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        pnlSearchNameLayout.setVerticalGroup(
            pnlSearchNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchNameLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblPrompt)
                .addGap(18, 18, 18)
                .addGroup(pnlSearchNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblResults, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addGap(626, 626, 626))
        );

        sclpSearchName.setViewportView(pnlSearchName);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sclpSearchName, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sclpSearchName, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNameCaretUpdate
        try
        {
            Connection conn = DriverManager.getConnection(DB_URL, "username", "password");
            Statement stmt = conn.createStatement();
            
            String results = "<html>";
            
            if (!txtName.getText().equals("") && !txtName.getText().equals(" "))
            {
                String sqlStmt = "SELECT * FROM Customer WHERE Name LIKE '%" + txtName.getText() + "%'";
                ResultSet result = stmt.executeQuery(sqlStmt);

                while (result.next())
                {
                    results += "ID: " + result.getObject(1) +
                               "<br/>Name: " + result.getObject(2) +
                               "<br/>Address: " + result.getObject(3) +
                               "<br/>Credit Limit: $" + f.format(result.getObject(4)) + 
                               "<br/><br/>";
                }
            }
            results += "</html>";

            if (results.equals("<html></html>"))
                    results = "No customers found with this name.";
            
            lblResults.setText(results);
            
            conn.close();
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "There was an error loading the database:\n" + ex.getMessage(),
                                          "SQL Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "There was an error:\n" + ex.getMessage(),
                                          "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_txtNameCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchNameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchNameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchNameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchNameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchNameJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrompt;
    private javax.swing.JLabel lblResults;
    private javax.swing.JPanel pnlSearchName;
    private javax.swing.JScrollPane sclpSearchName;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
